name: Network runner - finalization simulator

on:
  push:
    branches:
    - master
    tags: '**'
  pull_request:
    branches:
    - master

jobs:
  build_base:
    name: Run sbt tests
    runs-on: ubuntu-latest
    container: mozilla/sbt
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Run tests
      shell: bash
      run: |
        sbt test
